spring:
  application:
    name: task-ms
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db_task_ms?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8081

user:
  service:
    url: http://localhost:8080